import {
	Link as ChakraLink,
	Grid,
	GridItem,
	Heading,
	VStack,
} from '@chakra-ui/react'
import type {Metadata} from 'next'
import NextLink from 'next/link'

export const metadata: Metadata = {
	title: 'About page',
	description: 'Generated by create next app',
}

export default function AboutLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<Grid flex="1" h="full" gridTemplateRows="auto 1fr" gap="5">
			<Heading>About us</Heading>
			<Grid gridTemplateColumns="240px 1fr" h="full" gap="5">
				<VStack align="start" bgColor="gray.subtle" p="5" borderRadius="20px">
					<ChakraLink asChild>
						<NextLink href="/about/contacts">Contacts</NextLink>
					</ChakraLink>
					<ChakraLink asChild>
						<NextLink href="/about/team">Our Team</NextLink>
					</ChakraLink>
				</VStack>
				<GridItem py="5">{children}</GridItem>
			</Grid>
		</Grid>
	)
}
