import type {Metadata} from 'next'
import Link from 'next/link'

export const metadata: Metadata = {
	title: 'About page',
	description: 'Generated by create next app',
}

export default function AboutLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<div>
			<h1>About us</h1>
			<ul>
				<li>
					<Link href="/about/team">Our Team</Link>
				</li>
				<li>
					<Link href="/about/contacts">Contacts</Link>
				</li>
			</ul>
			<div>{children}</div>
		</div>
	)
}
