import type {Metadata} from 'next'
import {Montserrat} from 'next/font/google'
import './globals.scss'
import {Container} from '@chakra-ui/react'
import {Footer, Header, Providers} from '@/components'
import type {NavLinks} from '@/components/Header'
import {Provider} from '@/components/ui/provider'

const montserrat = Montserrat({
	variable: '--font-main',
	subsets: ['latin', 'cyrillic'],
})

export const metadata: Metadata = {
	title: 'Next course by MishaNep',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en" className={montserrat.className} suppressHydrationWarning>
			<body>
				<Providers>
					<Provider>
						<Header />
						<main>
							<Container my="6" flex="1" display="flex" flexDirection="column">
								{children}
							</Container>
						</main>
						<Footer />
					</Provider>
				</Providers>
			</body>
		</html>
	)
}
