import type {Metadata} from 'next'
import {Montserrat} from 'next/font/google'
import './globals.scss'
import TheFooter from '@/components/TheFooter'
import TheHeader from '@/components/TheHeader'

const montserrat = Montserrat({
	variable: '--font-main',
	subsets: ['latin', 'cyrillic'],
})

export const metadata: Metadata = {
	title: 'Next course by MishaNep',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en" className={montserrat.className}>
			<body>
				<TheHeader />
				<main>{children}</main>
				<TheFooter />
			</body>
		</html>
	)
}
