import type {Metadata} from 'next'
import {Montserrat} from 'next/font/google'
import './globals.scss'
import {Container} from '@chakra-ui/react'
import {TheFooter, TheHeader} from '@/components'
import type {NavLinks} from '@/components/TheHeader'
import {Provider} from '@/components/ui/provider'

const montserrat = Montserrat({
	variable: '--font-main',
	subsets: ['latin', 'cyrillic'],
})

export const metadata: Metadata = {
	title: 'Next course by MishaNep',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en" className={montserrat.className} suppressHydrationWarning>
			<body>
				<Provider>
					<TheHeader navLinks={navLinks} />
					<main>
						<Container my="6" flex="1" display="flex" flexDirection="column">
							{children}
						</Container>
					</main>
					<TheFooter />
				</Provider>
			</body>
		</html>
	)
}

const navLinks: NavLinks = [
	{
		id: 1,
		url: '/',
		label: 'Home',
	},
	{
		id: 2,
		url: '/about',
		label: 'About',
	},
	{
		id: 3,
		url: '/blog',
		label: 'Blog',
	},
]
